
name: Deploy Frontend to S3

on:
  push:
    branches: [main, dev, prod, clean-up-and-deploy]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # To build the project
  build-zork-gpt:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v3
      - name: Installing Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Installing dependencies
        working-directory: ./frontend
        run: npm install
      - name: Building project
        working-directory: ./frontend
        run: CI=false DISABLE_ESLINT_PLUGIN=true npm run build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Deploy to S3 bucket
        working-directory: ./frontend
        run: aws s3 sync ./build/ s3://zork-gpt --delete